# Generated by Django 5.2.7 on 2026-02-06 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('video', 'Video'), ('imagen', 'Imagen'), ('texto', 'Texto')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, upload_to='recursos/')),
                ('url_video', models.URLField(blank=True)),
                ('texto', models.TextField(blank=True)),
                ('publicado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='contenido.seccion')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
