# Generated by Django 5.2.7 on 2026-02-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_recurso_blog_post_recurso_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='publicar_en_blog',
            field=models.BooleanField(default=False, help_text='Si esta activo, tambien se crea un post en el blog.'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='publicado',
            field=models.BooleanField(default=True, help_text='Si esta activo, el recurso se muestra en /recursos/.'),
        ),
    ]
