# Generated by Django 5.2.7 on 2026-02-06 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionPrivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_doctor', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_paciente', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(blank=True, help_text='Tema de foro que inicio la conversacion (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='foro.tema')),
            ],
            options={
                'unique_together': {('doctor', 'paciente')},
            },
        ),
        migrations.CreateModel(
            name='MensajePrivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_privados', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='accounts.conversacionprivada')),
            ],
        ),
    ]
